calculator: com.github.ericdahl.dropwizard_factors.core.BasicFactorCalculator

logging:
  loggers:
    "com.github.ericdahl.dropwizard_factors.core.BasicFactorCalculator": DEBUG

server:
  applicationConnectors:
  - type: http
    port: 8080